language: php

php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer install

script:
   - php vendor/bin/phpcs library tests --standard=build/phpcs/Joomla --report=summary -np